#!/usr/bin/env python
"""
demo_forecasting.py â€” Stage 5: CashFin ML Forecast Demo

Demonstrates:
  1. Synthetic historical dataset
  2. Feature engineering
  3. Chronological train/test split
  4. 7-day average baseline vs RandomForest evaluation
  5. Future cash-flow prediction (horizon configurable)
  6. Integration with CashFlowService (CONFIRMED_ONLY, FORECAST_INCLUDED, CONSERVATIVE)

NOTE: This demo uses SYNTHETIC data â€” not real financial data.
      The model's predictive accuracy on this dataset does not
      represent performance on real-world financial time series.

Run: python demo_forecasting.py [--horizon N]
"""

import argparse
import sys
import os
import io
from datetime import date, timedelta
from decimal import Decimal

# Ensure UTF-8 output encoding for Windows terminals
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

import numpy as np
import pandas as pd

# Allow running from backend/
sys.path.insert(0, os.path.dirname(__file__))

from app.ml.features import build_features
from app.ml.dataset import build_dataset
from app.ml.forecaster import ForecasterService
from app.services.forecast_service import ForecastService
from app.services.cash_flow import CashFlowService
from app.schemas.financial_state import (
    FinancialState, UpcomingPayable, UpcomingReceivable,
    ReceivableMode, ForecastMode, EventType
)

CURRENCY = "â‚¹"

def fmt(amount: float) -> str:
    sign = "+" if amount >= 0 else "-"
    return f"{sign}{CURRENCY}{abs(amount):,.0f}"


def load_synthetic_data(path: str) -> pd.DataFrame:
    """Load the synthetic historical CSV generated by generate_synthetic_transactions.py."""
    df = pd.read_csv(path, parse_dates=["transaction_date"])
    df["amount"] = df["amount"].astype(float).abs()
    return df


def generate_inline_transactions(num_days: int = 180, seed: int = 42) -> pd.DataFrame:
    """
    Generate synthetic transaction data inline (no CSV required).
    Includes realistic variability: weekends, recurring, irregular.
    """
    rng = np.random.default_rng(seed)
    rows = []
    start = date.today() - timedelta(days=num_days)

    for i in range(num_days):
        d = start + timedelta(days=i)
        is_weekend = d.weekday() >= 5

        # Recurring rent on the 1st
        if d.day == 1:
            rows.append({"transaction_date": d, "amount": 50000.0, "transaction_type": "EXPENSE"})

        # Payroll on 28th
        if d.day == 28:
            rows.append({"transaction_date": d, "amount": 150000.0, "transaction_type": "EXPENSE"})

        # Customer payments (weekdays mostly)
        if not is_weekend:
            if rng.random() < 0.75:
                amt = rng.uniform(5000, 40000)
                rows.append({"transaction_date": d, "amount": round(amt, 2), "transaction_type": "INCOME"})

        # Irregular expenses
        if rng.random() < 0.25:
            amt = rng.uniform(1500, 12000)
            rows.append({"transaction_date": d, "amount": round(amt, 2), "transaction_type": "EXPENSE"})

        # Supplier payments every 14 days
        if i % 14 == 0:
            amt = rng.uniform(15000, 70000)
            rows.append({"transaction_date": d, "amount": round(amt, 2), "transaction_type": "EXPENSE"})

        # Occasional large customer payment
        if rng.random() < 0.05:
            amt = rng.uniform(50000, 150000)
            rows.append({"transaction_date": d, "amount": round(amt, 2), "transaction_type": "INCOME"})

    return pd.DataFrame(rows)


def print_divider(char="â”€", width=60):
    print(char * width)


def main(horizon_days: int = 30):
    print()
    print("=" * 60)
    print("  CashFin ML Forecast Demo â€” Stage 5")
    print("  NOTE: Using SYNTHETIC data â€” not real financial data")
    print("=" * 60)
    print()

    # â”€â”€ Load / generate data â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    csv_path = os.path.join(os.path.dirname(__file__), "data", "samples", "historical_transactions.csv")
    if os.path.exists(csv_path):
        df = load_synthetic_data(csv_path)
        print(f"Loaded synthetic data from: {csv_path}")
    else:
        print("Generating inline synthetic data (no CSV found)...")
        df = generate_inline_transactions(num_days=180)

    print(f"Total transaction rows : {len(df)}")
    dataset = build_dataset(df)
    if dataset is None or dataset.empty:
        print("ERROR: Insufficient data to build forecasting dataset.")
        sys.exit(1)

    total_days    = len(dataset)
    train_n       = int(total_days * 0.80)
    test_n        = total_days - train_n
    date_min      = dataset["date"].min().date()
    date_max      = dataset["date"].max().date()

    print(f"Historical days (after aggregation): {total_days}")
    print(f"Date range: {date_min} â†’ {date_max}")
    print()

    # â”€â”€ Train & evaluate â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    print_divider()
    print("Training models (chronological split, no shuffling)...")
    print(f"  Training set : {train_n} days")
    print(f"  Test set     : {test_n} days")
    print_divider()

    forecaster = ForecasterService(random_state=42)
    metrics = forecaster.train_and_evaluate(df, test_size=0.20)

    if "error" in metrics:
        print(f"\nERROR: {metrics['error']}")
        sys.exit(1)

    print()
    print("  Model: RandomForestRegressor (random_state=42)")
    print(f"  Training period : {metrics['train_start_date']} â†’ {metrics['train_end_date']}")
    print(f"  Test period     : {metrics['test_start_date']} â†’ {metrics['test_end_date']}")
    print()

    b_mae  = metrics["baseline_mae"]
    b_rmse = metrics["baseline_rmse"]
    b_r2   = metrics["baseline_r2"]
    rf_mae  = metrics["rf_mae"]
    rf_rmse = metrics["rf_rmse"]
    rf_r2   = metrics["rf_r2"]
    impr    = metrics["improvement_over_baseline_pct"]

    print(f"  {'Metric':<12}  {'Baseline (7d avg)':<22}  {'RandomForest':<22}")
    print(f"  {'â”€'*12}  {'â”€'*22}  {'â”€'*22}")
    print(f"  {'MAE':<12}  {CURRENCY}{b_mae:>18,.0f}    {CURRENCY}{rf_mae:>18,.0f}")
    print(f"  {'RMSE':<12}  {CURRENCY}{b_rmse:>18,.0f}    {CURRENCY}{rf_rmse:>18,.0f}")
    print(f"  {'RÂ²':<12}  {b_r2:>22.4f}  {rf_r2:>22.4f}")
    print()

    if impr > 0:
        print(f"  âœ“ RandomForest improves on baseline by {impr:.1f}%")
        selected_model = "RandomForestRegressor"
    elif impr < -5:
        print(f"  âœ— RandomForest underperforms baseline by {abs(impr):.1f}%")
        print(f"  â†’ Baseline selected as preferred forecasting method for this dataset.")
        selected_model = "7-day Historical Average (Baseline)"
    else:
        print(f"  â‰ˆ RandomForest is comparable to baseline (Î”={impr:.1f}%)")
        selected_model = "RandomForestRegressor"
    print(f"  Selected model: {selected_model}")
    print()

    # â”€â”€ Forecast future horizon â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    print_divider()
    print(f"  Cash-Flow Forecast â€” Next {horizon_days} Days")
    print_divider()

    predictions = forecaster.predict_next_days(df, horizon_days=horizon_days)

    print(f"  {'Date':<14} {'Predicted Net Flow':>22}  {'Â±MAE Range':>28}")
    print(f"  {'â”€'*14} {'â”€'*22}  {'â”€'*28}")
    for p in predictions:
        pred = p["predicted_amount"]
        mae  = p["historical_mae"]
        lo   = pred - mae
        hi   = pred + mae
        print(
            f"  {str(p['date']):<14} {fmt(pred):>22}  "
            f"[{fmt(lo)} .. {fmt(hi)}]"
        )

    print()
    print(f"  Note: Â±MAE range is an approximate heuristic uncertainty estimate")
    print(f"        (historical MAE = {CURRENCY}{rf_mae:,.0f}), NOT a statistically")
    print(f"        valid prediction interval.")
    print()

    # â”€â”€ Integration with CashFlowService â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    print_divider()
    print("  Integration with CashFlowService")
    print_divider()

    forecast_svc = ForecastService()
    forecast_svc.forecaster = forecaster
    forecast = forecast_svc.generate_forecast(df, company_id=1, horizon_days=horizon_days)

    state = FinancialState(
        company_id=1,
        as_of_date=date.today(),
        current_cash=Decimal("250000.00"),
        pending_payables_total=Decimal("0.00"),
        pending_receivables_total_raw=Decimal("0.00"),
        pending_receivables_total_adjusted=Decimal("0.00"),
        upcoming_payables=[
            UpcomingPayable(id=1, amount=Decimal("50000.00"),
                            due_date=date.today() + timedelta(days=5),
                            description="Supplier Invoice #1001"),
            UpcomingPayable(id=2, amount=Decimal("150000.00"),
                            due_date=date.today() + timedelta(days=15),
                            description="Payroll"),
        ],
        upcoming_receivables=[
            UpcomingReceivable(id=1, amount=Decimal("80000.00"),
                               expected_date=date.today() + timedelta(days=7),
                               confidence=Decimal("0.85"),
                               description="Customer A invoice"),
        ]
    )

    modes = [
        (ForecastMode.CONFIRMED_ONLY, "CONFIRMED_ONLY"),
        (ForecastMode.FORECAST_INCLUDED, "FORECAST_INCLUDED"),
        (ForecastMode.CONSERVATIVE, "CONSERVATIVE"),
    ]

    for fm, label in modes:
        proj = CashFlowService.calculate_projection(
            state=state,
            minimum_cash_buffer=Decimal("50000.00"),
            receivable_mode=ReceivableMode.RAW,
            forecast_mode=fm,
            forecast=forecast,
        )
        confirmed_count = sum(1 for e in proj.events if not e.is_predicted)
        predicted_count = sum(1 for e in proj.events if e.is_predicted)
        breach_msg = ""
        if proj.days_to_buffer_breach is not None:
            breach_msg = f"  âš  Buffer breach in {proj.days_to_buffer_breach} days"
        if proj.days_to_zero is not None:
            breach_msg += f"  âš  Zero-cash in {proj.days_to_zero} days"

        print(f"  [{label}]")
        print(f"    Confirmed events : {confirmed_count}")
        print(f"    Predicted events : {predicted_count}")
        if breach_msg:
            print(f"    {breach_msg}")
        else:
            print(f"    No cash-floor breach detected in projection")
        print()

    # â”€â”€ Key events â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    print_divider()
    print("  Sample Combined Event Timeline (FORECAST_INCLUDED)")
    print_divider()
    proj_combined = CashFlowService.calculate_projection(
        state=state,
        minimum_cash_buffer=Decimal("50000.00"),
        forecast_mode=ForecastMode.FORECAST_INCLUDED,
        forecast=forecast,
    )
    # Print up to 8 events for brevity
    for e in proj_combined.events[:8]:
        tag    = "PREDICTED" if e.is_predicted else "CONFIRMED"
        amount = float(e.amount)
        print(f"  {str(e.date):<14} {e.event_type.value:<10}  {fmt(amount):>18}  [{tag}]")
        if e.description:
            print(f"               {e.description}")
    if len(proj_combined.events) > 8:
        print(f"  ... and {len(proj_combined.events) - 8} more events")
    print()

    print_divider()
    print("  ARCHITECTURE REMINDER")
    print("  ML model PREDICTS uncertain cash flows.")
    print("  Deterministic DecisionEngine DECIDES payment strategy.")
    print("  These responsibilities are NEVER reversed.")
    print_divider()
    print()
    print("Demo complete.")
    print()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="CashFin ML Forecast Demo")
    parser.add_argument("--horizon", type=int, default=30, help="Forecast horizon in days (default: 30)")
    args = parser.parse_args()
    main(horizon_days=args.horizon)
