"""add_fingerprint_and_external_ids

Revision ID: 8a79b58b0a63
Revises: b9e7f4648c95
Create Date: 2026-08-31 22:15:59.550041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a79b58b0a63'
down_revision: Union[str, Sequence[str], None] = 'b9e7f4648c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payables', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'payables', ['external_id'])
    op.add_column('receivables', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'receivables', ['external_id'])
    op.add_column('transactions', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_transactions_fingerprint'), 'transactions', ['fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_fingerprint'), table_name='transactions')
    op.drop_column('transactions', 'fingerprint')
    op.drop_constraint(None, 'receivables', type_='unique')
    op.drop_column('receivables', 'external_id')
    op.drop_constraint(None, 'payables', type_='unique')
    op.drop_column('payables', 'external_id')
    # ### end Alembic commands ###
